config/routes.rb
Eveskills::Application.routes.draw do
  resources :api_keys
  match 'api_keys/pull_data/:id' => 'api_keys#pull_data', :via => :put


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :api_keys
end

app/models/api_key.rb
# == Schema Information
#
# Table name: api_keys
#
#  id                 :integer          not null, primary key
#  verification_code  :string(255)
#  user_id            :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  eve_api_identifier :string(255)
#  char_sheet         :text(4294967296)
#  skill_sheet        :text(4294967296)
#  training_queue     :text(4294967296)
#

require 'Nokogiri'

class ApiKey < ActiveRecord::Base
  validates_presence_of :user_id, :verification_code, :eve_api_identifier
  #we need to validate that the key's have no spaces


  belongs_to :user
  
  attr_accessible :id, :verification_code, :eve_api_identifier, :char_sheet
  attr_accessible :user_id

  cattr_accessor :skip_callbacks

  before_save :populate_char_sheet, :populate_skill_sheet, :populate_training_queue, :unless => :skip_callbacks

  def populate_char_sheet
    self.char_sheet = get_api_results_for("CharacterSheet")
  end

  def populate_skill_sheet
    self.skill_sheet = get_api_results_for("SkillInTraining")
  end

  def populate_training_queue
    self.training_queue = get_api_results_for("SkillQueue")
  end

  def char_sheet_is_valid?
    self.char_sheet.nil? ? false : true
  end

  def skill_sheet_is_valid?
    self.skill_sheet.nil? ? false : true
  end

  def training_queue_is_valid?
    self.training_queue.nil? ? false : true
  end

  def character_name
    character_name = get_character_name(xml_version(char_sheet))
  end

  def character_attributes
    attributes = get_attributes(xml_version(char_sheet))
  end

  def skill_in_training?
    api = xml_version(skill_sheet)
    is_skill_in_training(api)
  end

  def name_of_skill_in_training
    api = xml_version(skill_sheet)
    if skill_in_training?
      get_name_of_skill_in_training(api)
    end
  end

  def current_skill_training_end_time
    api = xml_version(skill_sheet)
    if skill_in_training?
      get_skill_training_end_time(api)
    end
  end

  def skill_training_queue
    api = xml_version(training_queue)
    skill_in_training? ? get_training_queue(api) : []
  end

  private

      def get_api_results_for(specific_api)
        api_results = Nokogiri.XML(open("https://api.eveonline.com/char/#{specific_api}.xml.aspx?keyID=#{self.eve_api_identifier}&vCode=#{self.verification_code}")) 
        api_results.at("//result/*") ? api_results.to_s : nil
      end

      def get_character_name(api)
        api.xpath("//name").inner_text
      end

      def get_attributes(api)
        result = api.at('attributes').children.each_with_object({}){ |o,h| h[o.name.to_sym] = o.text }
        # We have to delete the element :text from the results hash because
        # I have not found a more elegant way to collect the data without
        # :text element in the first place
        result.delete(:text)
        result
      end

      def is_skill_in_training(api)
        api.xpath("//skillInTraining").inner_text.to_bool
      end

      def get_name_of_skill_in_training(api)
        api.xpath("//trainingTypeID").inner_text
      end

      def get_skill_training_end_time(api)
        Time.zone.parse(api.xpath("//trainingEndTime").inner_text).utc
      end

      def get_training_queue(api)
        api.xpath("//row").map do |row|
          Hash[ row.attributes.map { |k, v| [k.to_sym, v.to_s] } ]
        end
      end

      def xml_version string
        Nokogiri::XML(string)
      end
end

app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @api_keys = ApiKey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @api_keys }
    end
  end

  def show
    @api_key = ApiKey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @api_key }
    end
  end

  def new
    @api_key = ApiKey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api_key }
    end
  end

  def edit
    @api_key = ApiKey.find(params[:id])
  end

  def create
    @api_key = ApiKey.new(params[:api_key])
    @api_key.user = current_user

    respond_to do |format|
      if @api_key.save
        format.html { redirect_to @api_key, notice: 'Api key was successfully created.' }
        format.json { render json: @api_key, status: :created, location: @api_key }
      else
        format.html { render action: "new" }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @api_key = ApiKey.find(params[:id])

    respond_to do |format|
      if @api_key.update_attributes(params[:api_key])
        format.html { redirect_to @api_key, notice: 'Api key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @api_key = ApiKey.find(params[:id])
    @api_key.destroy

    respond_to do |format|
      format.html { redirect_to api_keys_url }
      format.json { head :no_content }
    end
  end

  def pull_data
    @api_key = ApiKey.find(params[:id])
    @api_key.populate_char_sheet
    @api_key.populate_skill_sheet
    @api_key.populate_training_queue
    @api_key.skip_callbacks = true #because before_save calls populate_char_sheet
    # I never set the above value back to false because I am of the understanding
    # that this class attribute only persists for this instance, as long as it is
    # not used again this instance, this should not be a problem.

    respond_to do |format|
      if @api_key.update_attributes(params[:api_key])
        format.html { redirect_to @api_key, notice: 'Api key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_key.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

app/views/api_keys/_form.html.erb
<%= simple_form_for(@api_key) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :eve_api_identifier %>
    <%= f.input :verification_code %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/api_keys/edit.html.erb
<h1>Editing api_key</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_key %> |
<%= link_to 'Back', api_keys_path %>

app/views/api_keys/index.html.erb
<h1>Listing api_keys</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Eve api identifier</th>
    <th>Verification code</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>

  </tr>

<% @api_keys.each do |api_key| %>
  <tr>
    <td><%= api_key.id %></td>
    <td><%= api_key.eve_api_identifier %></td>
    <td><%= api_key.verification_code %></td>
    <td><%= api_key.user.name %></td>
    <td><%= link_to 'Show', api_key %></td>
    <td><%= link_to 'Edit', edit_api_key_path(api_key) %></td>
    <td><%= link_to 'Destroy', api_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <th><%= link_to 'pull_data', api_key, method: :put %></th>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Api key', new_api_key_path %>

app/views/api_keys/new.html.erb
<h1>New api_key</h1>
<p>Please ensure Eve api keys have an access mask of 393224</p>
<%= render 'form' %>

<%= link_to 'Back', api_keys_path %>

app/views/api_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @api_key.id %>
</p>

<p>
  <b>Eve Api Id:</b>
  <%= @api_key.eve_api_identifier %>
</p>

<p>
  <b>Verification code:</b>
  <%= @api_key.verification_code %>
</p>

<p>
  <b>User:</b>
  <%= @api_key.user.name %>
</p>

<p>
    <b>Character Name:<b>
    <%= @api_key.character_name %>
</p>

<p>
    <b>Character attributes:<b>
    <%= @api_key.character_attributes %>
</p>

<p>
    <b>Skill in training?:<b>
    <%= @api_key.skill_in_training? %>
</p>

<p>
    <b>Name of skill in training:<b>
    <%= @api_key.name_of_skill_in_training %>
</p>

<p>
    <b>Skill training end time:<b>
    <%= @api_key.current_skill_training_end_time %>
</p>

<p>
    <b>Skill training queue:<b>
      <% @api_key.training_queue.each do |queued| %>
          <%= queued %>
      <% end %>
</p>

<p>
    <b>Char Sheet:</b>
    <%= @api_key.char_sheet %>
</p>

<%= link_to 'Edit', edit_api_key_path(@api_key) %> |
<%= link_to 'Back', api_keys_path %>